### ISSUE TITLE
Avoid a global transform stream

### ISSUE THREAD

**Issue by mcollina** [nodeshift/opossum-hystrix#9]
I'm seeing some warnings about the number of listeners on EventEmitter if multiple instances of `HystrixStats` are created within the same application. These are caused by the global Transform stream in https://github.com/nodeshift/opossum-hystrix/blob/fa03ab0454ae8ab236976fd35352988d3fdec5a1/lib/hystrix-stats.js#L6-L12.

I would recommend to move this inside `HystrixStats` object itself, so that each instance of the stats object can be run inside the same Node.js process. This will change the example to:

```js

const CircuitBreaker = require('opossum');
  const HystrixStats = require('opossum-hystrix');
  const express = require('express');

  const app = express();
  app.use('/hystrix.stream', hystrixStream);

  // create a couple of circuit breakers
  const c1 = new CircuitBreaker(someFunction);
  const c2 = new CircuitBreaker(someOtherfunction);

  // Provide them to the constructor
  const hystrixMetrics = new HystrixStats([c1, c2]);

  // Provide a Server Side Event stream of metrics data
  function hystrixStream (request, response) {
      response.writeHead(200, {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive'
        });
      response.write('retry: 10000\n');
      response.write('event: connecttime\n');

      // Old: HystrixStats.stream.pipe(response);
      hystrixMetrics.stream.pipe(response);
    };
  }
```

I'm happy to send a PR

**Comment by lholmquist** [comment]
> I'm happy to send a PR

That would be great :)
